### ISSUE TITLE
Difficulties with macos-latest in build.yml

### ISSUE THREAD

**Issue by simonjwright** [alire-project/alire-index-checks#17]
This is prompted by macOS failures in [PR 1053](https://github.com/alire-project/alire-index/pull/1053).

I don’t understand why there should be macOS issues at all since the crate declares itself only available on Linux! but, if it was available on macOS, there would still be issues.

Both `(MacPorts) / macos-latest` and `(alr dev) / macos-latest` fail at the `Set up devel alr` step -- why does MacPorts need to do this?

I’d have expected the script to use `alire-project/setup-alire@v3`, not `@v2`.

The script runs-on macos-latest. Unfortunately, Github has silently updated macos-latest so it’s macos-14, i.e. aarch64!! The stable `alr` is an x86_64 build, which will run under Rosetta and look for and run an x86_64 compiler; if that succeeds, any resulting executable will also be x86_64, causing issues with any external crate that provides aarch64 libraries. 

So, why did `Set up devel alr` fail while attempting to built `alr`?

The answer is [here](https://github.com/alire-project/alire-index/actions/runs/8946905445/job/24578177366?pr=1053#step:4:647): this is the problem discussed [here](https://github.com/simonjwright/xcode_15_fix) (solution already applied to the aarch64 GCC compiler available at [GNAT FSF Builds](https://github.com/alire-project/GNAT-FSF-builds/releases/tag/gnat-13.2.0-2), but not to the x86_64 compiler).

The default Xcode in macos-14 is v15.0.1. Sadly, so is the default in macos-13. 
Possible fixes:
* select a version of Xcode which avoids the linking problem (14.2/3 for preference). I quite like the suggestions [here](https://gist.github.com/fabianfett/fd811d7921eb856bb100c5c15565077f).
* include the Xcode 15 fix in the x86_64 compiler.
* for macos-14, provide `alr` in aarch64 (see previous remarks about universal builds) so it picks the fixed compiler.
* run on macos-12.

**Comment by simonjwright** [comment]
Also, should we be using `actions/checkout@v4`?

**Comment by simonjwright** [comment]
> Both (MacPorts) / macos-latest and (alr dev) / macos-latest fail at the Set up devel alr step -- why does MacPorts need to do this?

Yes. The PR wanted to merge into `alire-project:stable-1.3.0`, so why did this script section choose the `devel-` path?

```
    # By default, this sets up the newest indexed native toolchain
    - name: Set up stable `alr`
      if: contains(github.base_ref, 'stable-')
      uses: alire-project/setup-alire@v2

    # By default, this sets up the newest indexed native toolchain
    - name: Set up devel `alr`
      if: contains(github.base_ref, 'devel-')
      uses: alire-project/setup-alire@v2
      with:
        branch: 'master'
```

(BTW, the comments aren’t right - or, at least one of them isn’t!)
